const datalar = [
  {
    id: "1",
    name: "JOHN WILLIAMS",
    album:
      "Star Wars ‘The Empire Strikes Back’ Original Motion Picture Soundtrack",
    desc: "Double Vinyl LP",
    cost: "£29.99",
    img: "https://www.emp.co.uk/dw/image/v2/BBQV_PRD/on/demandware.static/-/Sites-master-emp/default/dw9cf2be52/images/4/8/7/6/487698.jpg?sfrm=png",
  },
  {
    id: "2",
    name: "PINK FLOYD",
    album: "The Dark Side Of The Moon: Vinyl Reissue",
    desc: "Vinyl LP",
    cost: "£20.99",
    img: "https://dvfnvgxhycwzf.cloudfront.net/media/SharedImage/image550/.f0wj57gX/SharedImage-116561.jpg?t=e810278a06fcc3b7aa14",
  },
  {
    id: "3",
    name: "DAFT PUNK",
    album:
      "TRON: Legacy Reconfigured: Double Vinyl Edition [200 Copies Available]",
    desc: "Doble Vinyl LP",
    cost: "£29.99",
    img: "https://dvfnvgxhycwzf.cloudfront.net/media/SharedImage/image550/.fdxJO-_X/SharedImage-133785.jpg?t=abc98b90b586e37c25a1",
  },
  {
    id: "4",
    name: "U2",
    album: "Songs of Surrender",
    desc: "Doble Vinyl LP",
    cost: "£34.99",
    img: "https://dvfnvgxhycwzf.cloudfront.net/media/SharedImage/image550/.fqndtgWY/SharedImage-146943.png?t=e889aa3e85d120e40903",
  },
  {
    id: "5",
    name: "DAVID BOWIE",
    album: "Aladdin Sane: 50th Anniversary Limited Edition Half-Speed Master",
    desc: "Vinyl LP",
    cost: "£37.99",
    img: "https://dvfnvgxhycwzf.cloudfront.net/media/SharedImage/image550/.fCEx3WWY/SharedImage-146849.jpg?t=4b29c889ac325bbb5c91",
  },
  {
    id: "6",
    name: "JAMIROQUAI",
    album:
      "Everybody's Going to the Moon: 180 Gram Vinyl with Foil Numbered Sleever",
    desc: "Vinyl LP",
    cost: "£11.99",
    img: "https://dvfnvgxhycwzf.cloudfront.net/media/SharedImage/image550/.f3Lqv8MY/SharedImage-141378.png?t=4098594cbaa54999389a",
  },
  {
    id: "7",
    name: "THE ROLLING STONES",
    album:
      "The Rolling Stones In Mono: Limited Edition Colour Vinyl 16LP Box Set",
    desc: "Vinyl Box Set",
    cost: "£372.99",
    img: "https://superdeluxeedition.com/wp-content/uploads/2022/07/mono_cover.jpg",
  },
  {
    id: "8",
    name: "ALICE IN CHAINS",
    album: "Dirt: Limited Edition Yellow Vinyl 2LP [50 Copies Available Only",
    desc: "Doble Vinyl LP",
    cost: "£44.99",
    img: "https://dvfnvgxhycwzf.cloudfront.net/media/SharedImage/image550/.fuiDmRKY/SharedImage-139543.jpg?t=30b0426162db780cfd39",
  },
  {
    id: "9",
    name: "RED HOT CHILI PEPPERS",
    album: "Californication: Limited Copies Vinyl 2LP",
    desc: "Doble Vinyl LP",
    cost: "£30.99",
    img: "https://dvfnvgxhycwzf.cloudfront.net/media/SharedImage/image550/.fRvgblWY/SharedImage-146972.jpg?t=15cb53c7268a2ce4179b",
  },
  {
    id: "10",
    name: "METALLICA",
    album: "Master Of Puppets: LP",
    desc: "Vinyl LP",
    cost: "£31.99",
    img: "https://dvfnvgxhycwzf.cloudfront.net/media/SharedImage/image550/.f9KRFlIY/SharedImage-138612.jpg?t=1caa95a31387952a9eaf",
  },
  {
    id: "11",
    name: "KEANE",
    album: "Under The Iron Sea: Vinyl Edition [200 Copies Available]",
    desc: "Vinyl LP",
    cost: "£19.99",
    img: "https://dvfnvgxhycwzf.cloudfront.net/media/SharedImage/image550/.fOOP7tsW/SharedImage-91582.png?t=fb31676c9de0360e0f61",
  },
  {
    id: "12",
    name: "JOHNNY CASH",
    album: "American V: A Hundred Highways",
    desc: "Vinyl LP",
    cost: "£22.99",
    img: "https://dvfnvgxhycwzf.cloudfront.net/media/SharedImage/image550/.f5JvjBcU/SharedImage-30318.jpg?t=ae6e328c6c1e91edb199",
  },
  {
    id: "13",
    name: "RAMMSTEIN",
    album: "RAMMSTEIN",
    desc: "Double Vinyl LP",
    cost: "£29.99",
    img: "https://dvfnvgxhycwzf.cloudfront.net/media/SharedImage/image550/.f2BqFxoW/SharedImage-90052.jpg?t=2f34a021a8be6e163758",
  },
  {
    id: "14",
    name: "R.E.M.",
    album:
      "New Adventures In Hi-Fi (25th Anniversary Edition): Limited Edition 2LP",
    desc: "Double Vinyl LP",
    cost: "£37.99",
    img: "https://dvfnvgxhycwzf.cloudfront.net/media/SharedImage/image550/.f2p6xytX/SharedImage-124123.png?t=e43cd1a81e2cdaa9bc36",
  },
  {
    id: "15",
    name: "GUNS N' ROSES",
    album: "Greatest Hits Vinyl",
    desc: "Double Vinyl LP",
    cost: "£31.99",
    img: "https://dvfnvgxhycwzf.cloudfront.net/media/SharedImage/image550/.fC8duaOX/SharedImage-106669.jpg?t=74f1793c781fa085eb5d",
  },
];
export default datalar;
